apiVersion: v1
kind: ReplicationController
metadata:
  name: myjavaapp-rc
spec:
  replicas: 3
  selector:
    app: myaapp
  template:
    metadata:
      labels:
        app: myaapp
    spec:
      containers:
        - name: myapp-container
          image: maha4iac/mahaonlinestore:1
          ports:
            - containerPort: 8080
